spring:
  application:
    name: spring-demo
  profiles.active: dev
  datasource:
    url: jdbc:h2:mem:db
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
  activemq:
    queue-name: my_queue

server:
  port: 9000